live_config_reload = true

import = ["~/.config/alacritty/themes/themes/catppuccin_latte.toml"]
# gnome_terminal.toml
[env]
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"
TERM = "alacritty"

[font]
size = 15.0

[font.glyph_offset]
x = 0
y = 7

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
# family = "IosevkaTerm Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 17

[[keyboard.bindings]]
chars = '\p'
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = '\n'
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[scrolling]
history = 10000
multiplier = 1


[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "Buttonless"
dynamic_padding = true
opacity = 0.9
blur = true


[window.padding]
x = 10
y = 0
