live_config_reload = true

import = ["~/.config/alacritty/themes/Cobalt2.yml"]

[env]
TERM = "alacritty"

[font]
size = 14.0

[font.bold]
family = "MonoLisa"
style = "Bold"

[font.bold_italic]
family = "MonoLisa"
style = "Italic"

[font.glyph_offset]
x = 0
y = 7

[font.italic]
family = "MonoLisa"
style = "Italic"

[font.normal]
family = "MonoLisa Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 14

[[keyboard.bindings]]
chars = '\p'
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = '\n'
key = "RBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[scrolling]
history = 100000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "Buttonless"
dynamic_padding = true

[window.padding]
x = 10
y = 10
